package com.hanker.model;

public enum EmailConstants {

	LOGIN_STATE_NOT_READY,
	LOGIN_STATE_FAILED_BY_NETWORK,
	LOGIN_STATE_FAILED_BY_CREDENTIALS,
	LOGIN_STATE_SUCCESS,
	
	MESSAGE_SENT_OK,
	MESSAGE_SENT_ERROR
	
}
